# Generated by Django 6.0.5 on 2026-05-31 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.PositiveIntegerField(unique=True, verbose_name='Sr No.')),
                ('date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Loan Amount (₹)')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Interest (₹)')),
                ('interest_rate', models.CharField(default='0%', max_length=10, verbose_name='Interest Rate')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Final Amount (₹)')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('emergency', 'Emergency')], default='pending', max_length=20, verbose_name='Status')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balance Due (₹)')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='Remark')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Record',
                'verbose_name_plural': 'Loan Records',
                'ordering': ['sr'],
            },
        ),
    ]
